### ISSUE TITLE
Defguard enrollment should not enforce phone number

### ISSUE THREAD

**Issue by syphernl** [DefGuard/client#217] opened 2024-03-14 07:58 UTC
Is there a reason the enrollment process in the client expects the user to enter their phone number? 

I understand why it would need an email but what is the reasoning behind requiring a phone number? Luckily `00000` is accepted so that can be used as a workaround for people who prefer not to enter their phone number.

**Comment by teon** [comment] 2024-03-14 11:16
Duplicate of https://github.com/DefGuard/proxy/issues/52

**Closed by teon** 2024-03-14 11:16 UTC
